export const GET_FOOD_SUCCESS = "GET_FOOD_SUCCESS";
export const GET_FOOD_FAILED = "GET_FOOD_FAILED";
export const GET_FOODMENUS_ID_SUCCESS = "GET_FOODMENUS_ID_SUCCESS";
export const GET_FOODMENUS_ID_FAILED = "GET_FOODMENUS_ID_FAILED";
